/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shi_androidstudy_ndk_MainActivity */

#ifndef _Included_com_shi_androidstudy_ndk_MainActivity
#define _Included_com_shi_androidstudy_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shi_androidstudy_ndk_MainActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_shi_androidstudy_ndk_MainActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_shi_androidstudy_ndk_MainActivity
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_shi_androidstudy_ndk_MainActivity_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_shi_androidstudy_ndk_MainActivity
 * Method:    encryptPassword
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_shi_androidstudy_ndk_MainActivity_encryptPassword
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_shi_androidstudy_ndk_MainActivity
 * Method:    encryptString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shi_androidstudy_ndk_MainActivity_encryptString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
