/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shi_androidstudy_ndk_MainActivity */

#ifndef _Included_com_shi_androidstudy_ndk_MainActivity
#define _Included_com_shi_androidstudy_ndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shi_androidstudy_ndk_MainActivity
 * Method:    useJavah
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shi_androidstudy_ndk_MainActivity_useJavah
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
