/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shi_androidstudy_myjni_MainActivity */

#ifndef _Included_com_shi_androidstudy_myjni_MainActivity
#define _Included_com_shi_androidstudy_myjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shi_androidstudy_myjni_MainActivity
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shi_androidstudy_myjni_MainActivity_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
